#!/usr/bin/env python3
"""The build stamp: what a running build reports as its version.

GridFPV's rule, adopted here: **a release names itself, everything else names
its commit.**

1. ``SPLITTER_RELEASE_VERSION`` env (leading ``v`` stripped) — explicit override
   for a pipeline that knows what it ships.
2. HEAD exactly on a *clean* ``v*`` tag ⇒ the tag minus the ``v`` (``0.1.0``).
   ``dev-*`` tags deliberately do not match: those builds must not look like
   releases.
3. Otherwise ⇒ ``<pyproject version>-dev-<short hash>``, ``-dirty`` appended
   when the tree has uncommitted changes.
4. No usable git (a source tarball) ⇒ the pyproject version verbatim.

    python scripts/stamp.py            # print it
    python scripts/stamp.py --write    # also write src/splitter/_stamp.py (gitignored)
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from collections.abc import Mapping
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STAMP_FILE = ROOT / "src" / "splitter" / "_stamp.py"


def _git(*args: str, cwd: Path = ROOT) -> str | None:
    try:
        out = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, check=False)
    except OSError:
        return None
    if out.returncode != 0:
        return None
    return out.stdout.strip() or None


def base_version(root: Path = ROOT) -> str:
    text = (root / "pyproject.toml").read_text(encoding="utf-8")
    m = re.search(r'^version\s*=\s*"([^"]+)"', text, re.M)
    return m.group(1) if m else "0.0.0"


def build_stamp(root: Path = ROOT, env: Mapping[str, str] | None = None) -> str:
    e: Mapping[str, str] = os.environ if env is None else env
    override = e.get("SPLITTER_RELEASE_VERSION", "").strip()
    if override:
        return override.lstrip("v")
    pkg = base_version(root)
    dirty = _git("status", "--porcelain", cwd=root) is not None
    if not dirty:
        tag = _git("describe", "--exact-match", "--tags", "--match", "v*", "HEAD", cwd=root)
        if tag:
            return tag.lstrip("v")
    short = _git("rev-parse", "--short=7", "HEAD", cwd=root)
    if not short:
        return pkg
    base = pkg.split("-", 1)[0]
    return f"{base}-dev-{short}{'-dirty' if dirty else ''}"


def write_stamp(stamp: str, path: Path = STAMP_FILE) -> None:
    path.write_text(
        '"""Generated by scripts/stamp.py at build time — do not edit or commit."""\n\n'
        f'STAMP = "{stamp}"\n',
        encoding="utf-8",
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="write src/splitter/_stamp.py")
    ap.add_argument("--stamp", default="", help="use this stamp instead of computing it")
    args = ap.parse_args()
    stamp = args.stamp.strip() or build_stamp()
    if args.write:
        write_stamp(stamp)
        print(f"wrote {STAMP_FILE.relative_to(ROOT)}: {stamp}", file=sys.stderr)
    print(stamp)


if __name__ == "__main__":
    main()
